# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment mappings (source of readable parameter names / javadoc)
parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10

## Environment properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.72
neo_version_range=[21.1.0,22.0)
loader_version_range=[1,)

## Mod properties
mod_id=woolproofed
mod_name=Woolproofed
mod_license=CC0-1.0
mod_version=1.0.1
mod_group_id=hu.snowylol.woolproofed
mod_authors=SSnowly, clamytoe
mod_description=A mod that blocks sounds when wool is placed between the sound source and the player.
